In [337]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [338]:
data = pd.read_csv('./datasets/2014-15 Perm.csv')
data.head()

,Team,G,W,L,WP,MP,FG,FGA,FG%,3P,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Golden State Warriors,82,67,15,81.7,240.6,41.6,87.0,0.478,10.8,...,0.768,10.4,34.3,44.7,27.4,9.3,6.0,14.5,19.9,110.0
1,Los Angeles Clippers,82,56,26,68.3,240.6,39.4,83.3,0.473,10.1,...,0.710,9.6,33.1,42.6,24.8,7.8,5.0,12.3,21.3,106.7
2,Dallas Mavericks,82,50,32,61.0,242.4,39.7,85.8,0.463,8.9,...,0.752,10.5,31.8,42.3,22.5,8.1,4.5,13.0,20.0,105.2
3,Toronto Raptors,82,49,33,59.8,242.1,37.9,83.3,0.455,8.9,...,0.787,10.7,30.8,41.5,20.7,7.5,4.4,12.9,20.9,104.0
4,Oklahoma City Thunder,82,45,37,54.9,241.8,38.8,86.8,0.447,7.7,...,0.754,12.8,34.7,47.5,20.5,7.3,5.5,14.7,22.3,104.0

In [339]:
data = data.drop(['Team','G','MP'],axis=1)
data.head()

,W,L,WP,FG,FGA,FG%,3P,3PA,3P%,2P,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,67,15,81.7,41.6,87.0,0.478,10.8,27.0,0.398,30.8,...,0.768,10.4,34.3,44.7,27.4,9.3,6.0,14.5,19.9,110.0
1,56,26,68.3,39.4,83.3,0.473,10.1,26.9,0.376,29.3,...,0.710,9.6,33.1,42.6,24.8,7.8,5.0,12.3,21.3,106.7
2,50,32,61.0,39.7,85.8,0.463,8.9,25.4,0.352,30.8,...,0.752,10.5,31.8,42.3,22.5,8.1,4.5,13.0,20.0,105.2
3,49,33,59.8,37.9,83.3,0.455,8.9,25.1,0.352,29.0,...,0.787,10.7,30.8,41.5,20.7,7.5,4.4,12.9,20.9,104.0
4,45,37,54.9,38.8,86.8,0.447,7.7,22.7,0.339,31.1,...,0.754,12.8,34.7,47.5,20.5,7.3,5.5,14.7,22.3,104.0

In [340]:
data.dtypes

W        int64
L        int64
WP     float64
FG     float64
FGA    float64
FG%    float64
3P     float64
3PA    float64
3P%    float64
2P     float64
2PA    float64
2P%    float64
FT     float64
FTA    float64
FT%    float64
ORB    float64
DRB    float64
TRB    float64
AST    float64
STL    float64
BLK    float64
TOV    float64
PF     float64
PTS    float64
dtype: object

In [341]:
data = data.drop(['3P%','2P%','FT%','FG%','FTA','3PA','2PA','FGA'],axis=1)

In [342]:
data['WP'].round(decimals=0)
data['WP'] = data['WP'].astype(int)

In [343]:
data.head()

,W,L,WP,FG,3P,2P,FT,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,67,15,81,41.6,10.8,30.8,16.0,10.4,34.3,44.7,27.4,9.3,6.0,14.5,19.9,110.0
1,56,26,68,39.4,10.1,29.3,17.9,9.6,33.1,42.6,24.8,7.8,5.0,12.3,21.3,106.7
2,50,32,61,39.7,8.9,30.8,16.9,10.5,31.8,42.3,22.5,8.1,4.5,13.0,20.0,105.2
3,49,33,59,37.9,8.9,29.0,19.3,10.7,30.8,41.5,20.7,7.5,4.4,12.9,20.9,104.0
4,45,37,54,38.8,7.7,31.1,18.6,12.8,34.7,47.5,20.5,7.3,5.5,14.7,22.3,104.0

In [344]:
y = (data['W'])
feature_names = [i for i in data.columns if data[i].dtype in [np.float64]]
X = data[feature_names]
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=1)
my_model = RandomForestClassifier(n_estimators=100,
                                  random_state=0).fit(train_X, train_y)

In [345]:
import eli5
from eli5.sklearn import PermutationImportance
from sklearn.svm import SVC

In [346]:
svc = SVC().fit(val_X, val_y)
perm = PermutationImportance(svc).fit(val_X, val_y)
eli5.show_weights(perm, feature_names=list(X.columns))